ALTER TABLE "users" ALTER COLUMN "avatar_url" SET DATA TYPE VARCHAR(2048);
ALTER TABLE "photos" ALTER COLUMN "url" SET DATA TYPE VARCHAR(2048),
ALTER COLUMN "thumbnail_url" SET DATA TYPE VARCHAR(2048);
